# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography - Antonio Suels "
subtitle: "the world, through my eyes"
tagline: "perosnal photography blog"
author: "Antonio Suels"
header:
 title: "Photography"
 subtitle: "by Antonio Suels"
footer:
 name: "Hey there, my name is Antonio"
 bio: "Venezuelan, engineer, living in Europe, exploring the world... with a camera!"
# github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
# web_design: "AJ"
social_urls:
  #twitter: "https://twitter.com/AntonioSuels"
  instagram: "https://www.instagram.com/kikiriguiki_photography/"
  #linkedin: "https://www.linkedin.com/in/antoniosuels"
  github: "https://github.com/kikiriguiki"
impressum:
  name: Antonio Suels 
  address: Munich, Germany
  email: eMail <a href="mailto:info@kikiriguiki.com?subject=%5Bwww.kikiriguiki.com%5D%20-%20Your%20Subject">click here</a>
  phone: phone +49 721 5604631
  source: <a href="https://www.e-recht24.de/impressum-generator.html">https://www.e-recht24.de/impressum-generator.html</a>

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
